# Generated by Django 4.0.6 on 2022-08-20 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Taken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200)),
                ('Protein', models.FloatField()),
                ('Fats', models.FloatField()),
                ('Carbohydrates', models.FloatField()),
                ('Calories', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Consumer_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_Consumed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caloriecounter_app.food_taken')),
                ('User_Detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
